from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from local_llm_bench.report import ensure_report_html


class ReportTests(unittest.TestCase):
    def test_ensure_report_html_creates_reuses_and_refreshes_stale_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            report_path = root / "docs" / "index.html"
            history_path = root / "runs" / "history.json"
            history_path.parent.mkdir(parents=True, exist_ok=True)
            history_path.write_text("[]", encoding="utf-8")

            created = ensure_report_html(report_path, history_path)
            original_text = report_path.read_text(encoding="utf-8")
            reused = ensure_report_html(report_path, history_path)
            report_path.write_text("sentinel", encoding="utf-8")
            refreshed = ensure_report_html(report_path, history_path)
            forced = ensure_report_html(report_path, history_path, force=True)
            refreshed_text = report_path.read_text(encoding="utf-8")

        self.assertTrue(created)
        self.assertFalse(reused)
        self.assertTrue(refreshed)
        self.assertTrue(forced)
        self.assertIn("../runs/history.json", original_text)
        self.assertIn("comparisonModelKey", original_text)
        self.assertIn("Benchmark ID", original_text)
        self.assertIn('data-sort="provider_sort">実行元</th>', original_text)
        self.assertIn('data-tab="compare"', original_text)
        self.assertIn('id="compare-left-model"', original_text)
        self.assertIn('id="leaderboard-model-filter"', original_text)
        self.assertIn('id="leaderboard-model-options"', original_text)
        self.assertIn('id="prompt-filter"', original_text)
        self.assertIn("ALL_PROMPTS", original_text)
        self.assertIn("renderPromptSelector", original_text)
        self.assertIn("leaderboardSelectedModels", original_text)
        self.assertIn("inferModelInfoFromModelName", original_text)
        self.assertIn("extractQuantizationToken", original_text)
        self.assertIn("looksLikeFileSystemPath", original_text)
        self.assertIn("Warm Score", original_text)
        self.assertIn("pp TPS", original_text)
        self.assertIn("tg TPS", original_text)
        self.assertIn("TPOT (ms/token)", original_text)
        self.assertIn('id="concurrency-body"', original_text)
        self.assertNotIn('id="performance-charts"', original_text)
        self.assertNotIn("renderPerformanceCharts", original_text)
        self.assertNotIn("performanceMemory", original_text)
        self.assertNotIn("Peak Mem", original_text)
        self.assertNotIn("入力長別の測定結果はありません", original_text)
        self.assertIn("Initial Prompt Speed", original_text)
        self.assertIn("Conversation Prompt Speed", original_text)
        self.assertIn("currentHasBenchmarkMetrics", original_text)
        self.assertIn('data-benchmark-column="true"', original_text)
        self.assertIn('id="leaderboard-note"', original_text)
        self.assertIn("未取得は0で補完しません", original_text)
        self.assertIn("Benchmark Error", original_text)
        self.assertIn('id="quality-body"', original_text)
        self.assertIn("リクエスト成功率とは区別", original_text)
        self.assertIn("Error Analysis", original_text)
        self.assertIn('data-tab="telemetry"', original_text)
        self.assertIn('id="telemetry-panel"', original_text)
        self.assertIn('id="telemetry-content"', original_text)
        self.assertIn("Run Averages", original_text)
        self.assertIn("Question Averages", original_text)
        self.assertIn("Generated size vs generation time", original_text)
        self.assertIn("Input context vs wait time", original_text)
        self.assertIn("Prompt growth vs wait time", original_text)
        self.assertIn("Averaged Turn Breakdown", original_text)
        self.assertIn("averageTelemetryRows", original_text)
        self.assertIn("telemetryExecutionRows", original_text)
        self.assertIn("turnInputGrowthTimePoints", original_text)
        self.assertIn("renderTelemetryPromptComposition", original_text)
        self.assertIn("turnUsageForRun", original_text)
        self.assertIn("renderTelemetry", original_text)
        self.assertIn("renderTelemetryScatterSvg", original_text)
        self.assertIn("renderTelemetryScatterChart", original_text)
        self.assertIn("tokenTimePoints", original_text)
        self.assertIn("telemetryForRun", original_text)
        self.assertIn('id="errors-panel"', original_text)
        self.assertIn('id="error-signature-table"', original_text)
        self.assertIn("renderErrorAnalysis", original_text)
        self.assertIn("resolveLogUrl", original_text)
        self.assertIn("ツール数", original_text)
        self.assertIn("summarizeCountMap", original_text)
        self.assertIn("計測サマリー", original_text)
        self.assertIn("会話・思考・ツール履歴", original_text)
        self.assertIn("inspectStorageLabel", original_text)
        self.assertIn('class="details-layout"', original_text)
        self.assertIn("選択中の run 詳細", original_text)
        self.assertNotEqual(refreshed_text, "sentinel")
